### MONITORS ###
source = ~/.config/yusa/yumonitor.conf

### MY PROGRAMS ###
source = ~/.config/yusa/yuprogram.conf

### AUTOSTART ###
source = ~/.config/yusa/yusaauto.conf

### ENVIRONMENT VARIABLES ###
source = ~/.config/yusa/yuenv.conf

### LOOK AND FEEL ##
source = ~/.config/yusa/yulooknfeel.conf

### KEYBINDINGS ###
source = ~/.config/yusa/yusabind.conf

### WINDOWS AND WORKSPACES ###
source = ~/.config/yusa/yuwinwork.conf