### MONITORS ###
source = ~/.config/yusa/myth/yumonitor.conf

### MY PROGRAMS ###
source = ~/.config/yusa/myth/yuprogram.conf

### AUTOSTART ###
source = ~/.config/yusa/myth/yusaauto.conf

### ENVIRONMENT VARIABLES ###
source = ~/.config/yusa/myth/yuenv.conf

### LOOK AND FEEL ##
source = ~/.config/yusa/myth/yulooknfeel.conf

### KEYBINDINGS ###
source = ~/.config/yusa/myth/yusabind.conf

### WINDOWS AND WORKSPACES ###
source = ~/.config/yusa/myth/yuwinwork.conf