exec-once = bash ~/.config/yusa/myth/yusa/yusa.sh
exec-once = bash ~/.config/yusa/myth/yusa/yustartup.sh
exec-once = bash ~/.config/yusa/myth/yusa/yusage.sh
exec-once = bash ~/.config/yusa/myth/yusa/yustar.sh
exec-once = waypaper --restore
exec-once = wal -r
exec-once = swaync
exec-once = nwg-look -a
exec-once = waybar