exec-once = bash ~/.config/yusa/yuarch.sh
exec-once = bash ~/.config/yusa/yumy.sh
exec-once = bash ~/.config/yusa/yuwaybar.sh
exec-once = waybar
exec-once = wal -r
exec-once = bash -c 'hyprctl dispatch exec hyprpaper & sleep 0.5; LAST_WALLPAPER_FILE="$HOME/.cache/last_wallpaper.txt"; if [ -f "$LAST_WALLPAPER_FILE" ]; then LAST_WALLPAPER=$(cat "$LAST_WALLPAPER_FILE"); MONITOR_NAME="HDMI-A-1"; hyprctl hyprpaper preload "$LAST_WALLPAPER"; hyprctl hyprpaper wallpaper "$MONITOR_NAME,$LAST_WALLPAPER"; fi'
exec-once = swww init
exec-once = swaync
exec-once = nwg-look -a
exec-once = waypaper --restore
exec-once = bash ~/.config/yusa/yustar.sh
