exec-once = bash ~/.config/yusa/yusage.sh
exec-once = bash ~/.config/yusa/yuarch.sh
exec-once = bash ~/.config/yusa/yusase.sh
exec-once = bash ~/.config/yusa/yumy.sh
exec-once = bash ~/.config/yusa/yustar.sh
exec-once = waypaper --restore
exec-once = wal -r
exec-once = swaync
exec-once = nwg-look -a
exec-once = waybar